---
- name: Install SSH authorized_keys on all hosts (optional)
  hosts: all
  become: true
  roles:
    - ssh_key

- name: Configure Primary Firewall
  hosts: firewalls_primary
  become: true
  roles:
    - firewall_primary

- name: Configure Backup Firewall
  hosts: firewalls_backup
  become: true
  roles:
    - firewall_backup

- name: Configure FTP Server
  hosts: ftp_servers
  become: true
  roles:
    - ftp_server

- name: Configure Client Downloader
  hosts: client_servers
  become: true
  roles:
    - downloader
