all:
  children:

    firewalls_primary:
      hosts:
        fw_primary:
          ansible_host: 3.137.3.144

    firewalls_backup:
      hosts:
        fw_backup:
          ansible_host: 3.128.5.57

    ftp_servers:
      hosts:
        server1:
          ansible_host: 172.31.102.41
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@FW_PRIMARY_PUBLIC_IP_HERE"

    client_servers:
      hosts:
        server2:
          ansible_host: 172.31.100.184
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@FW_PRIMARY_PUBLIC_IP_HERE"
