all:
  children:

    firewalls_primary:
      hosts:
        fw_primary:
          ansible_host: 3.137.3.144
          ansible_user: ubuntu

    firewalls_backup:
      hosts:
        fw_backup:
          ansible_host: 3.128.5.57
          ansible_user: ubuntu

    ftp_servers:
      hosts:
        server1:
          ansible_host: 172.31.102.41
          ansible_user: ubuntu
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@<PRIMARY FIREWALL EIP>"

    client_servers:
      hosts:
        server2:
          ansible_host: 172.31.100.184
          ansible_user: ubuntu
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@<PRIMARY FIREWALL EIP>"
