all:
  children:

    firewalls_primary:
      hosts:
        fw_primary:
          ansible_host: 172.31.101.11

    firewalls_backup:
      hosts:
        fw_backup:
          ansible_host: 172.31.103.11

    ftp_servers:
      hosts:
        server1:
          ansible_host: 172.31.102.41

    client_servers:
      hosts:
        server2:
          ansible_host: 172.31.100.184
