all:
  children:
    ftp:
      hosts:
        server1:
          ansible_host: <server1 private IP>
    downloader:
      hosts:
        server2:
          ansible_host: <server2 private IP>
    firewall_primary:
      hosts:
        fw_primary:
          ansible_host: <primary firewall private IP>
    firewall_backup:
      hosts:
        fw_backup:
          ansible_host: <backup firewall private IP>
